### ISSUE TITLE
Some problem

### ISSUE THREAD

**Issue by ronidab** [ronidab/chess#1]
https://github.com/ronidab/chess/blob/63f1ff4bfea8f612c725930d08732b8567cbb790/Checker.h#L33-L35
Hi, Misha. I have some problem here. Totally stuck. Please come and save me!!!!!
@mishashevelinn

**Comment by mishashevelinn** [comment]
Hi Roni. There is no problems. Code suppose to work.

**Comment by ronidab** [comment]
cheers mISHA
